### ISSUE TITLE
Deployment Steps Not Working - "docker-compose" Issue and Missing .env Configuration

### ISSUE THREAD

**Issue by yousri-meftah** [mohamad-liyaghi/FoodAnywhere#19]
I followed the deployment steps provided in the documentation, but encountered an issue. It seems that the instructions mention "docker compose" instead of "docker-compose," which may be causing the problem.

Additionally, there is no mention of configuring any .env files before running the project. Could you please confirm if a .env file is required, and if so, provide details on how to configure it?

Any guidance would be appreciated.

Thanks!

**Comment by mohamad-liyaghi** [comment]
Hi there. Env files are stored in `envs` folder. Each stage (local/production) has its own env file, so you dont need to add extra env file.

**Comment by yousri-meftah** [comment]
Thank you! How can I learn from you? I really admire your code, but I don't fully understand it. How can I improve my understanding?

**Comment by mohamad-liyaghi** [comment]
I believe the reason you might be having trouble understanding the system is that we currently don’t have any documentation available. We’re planning to add detailed documentation soon to make everything clearer. 
Btw, thanks for your nice comment.
